export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const CHOOSE_SEARCH_ADDRESS = 'CHOOSE_SEARCH_ADDRESS'
export const USER_CENTER_INFO = 'USER_CENTER_INFO'
export const MY_EXCHANGE_TAB = 'MY_EXCHANGE_TAB'
export const MY_GOOD_LIST_TAB = 'MY_GOOD_LIST_TAB'

